openapi: 3.0.3

info:
  version: 1.0.0
  title: ğŸš—[AOS 2023] Inventario de Recambios del taller ğŸš—
  description: >
    ## ğŸš˜ API REST para la gestiÃ³n de inventario de taller de coches
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  contact:
    name: Escuela TÃ©cnica Superior de IngenierÃ­a de Sistemas Informaticos
    url: 'https://www.etsisi.upm.es/'
    email: webmaster@etsisi.upm.es
servers:
  - url: http://127.0.0.1:80/api/v1
tags:
  - name: 'âš™ï¸Inventario'
  
paths:
  /recambios:
    $ref: "./paths/recambios.yaml"
  /recambios/{Numero_Serie}:
    $ref: "./paths/recambio.yaml"
components:
  schemas:
    $ref: "./schemas/_index.yaml"
  headers:
    $ref: "./headers/_index.yaml"
  parameters:
    $ref: "./parameters/_index.yaml"
  requestBodies:
    $ref: "./requestBodies/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"
  examples:
    $ref: "./examples/_index.yaml"